### ISSUE TITLE
更新逻辑询问

### ISSUE THREAD

**Issue by Stronking** [pooneyy/1024-Host-List#2]
您好，是否可以跟我讲一下地址获取逻辑？我看到你的action里面有一个从变量里面去url的   是否可以透露一下地址是什么？我的联系方式是zblyxcx@163.com，是否可以加一下微信或其他联系方式？

**Comment by pooneyy** [comment]
这个不能说。但是官方有[地址发布页](www.jklbn.xyz)，这个你能在技术讨论区置顶帖看到。
